export const LANDING_VIDEO_TEMPLATES = [
  {
    id: 'video-bullet-time',
    name: 'Bullet Time',
    img: 'https://lazykiwi.oss-accelerate.aliyuncs.com/web-assets/pic-references/home-cameramotion/bullet time.png',
    prompt: 'Create a cinematic slow-motion bullet time shot with dramatic camera orbit.',
  },
  {
    id: 'video-earth-zoom-out',
    name: 'Earth Zoom Out',
    img: 'https://lazykiwi.oss-accelerate.aliyuncs.com/web-assets/pic-references/home-cameramotion/earth zoom out.png',
    prompt: 'Start close to the subject, then zoom out rapidly into a breathtaking earth-scale view.',
  },
  {
    id: 'video-seamless-transition',
    name: 'Seamless Transition',
    img: 'https://lazykiwi.oss-accelerate.aliyuncs.com/web-assets/pic-references/home-cameramotion/seamless transition.png',
    prompt: 'Move smoothly from one scene into another with a hidden cinematic transition.',
  },
  {
    id: 'video-crash-zoom',
    name: 'Crash Zoom',
    img: 'https://lazykiwi.oss-accelerate.aliyuncs.com/web-assets/pic-references/home-cameramotion/crash zoom.png',
    prompt: 'Rush the camera toward the subject with a dramatic zoom burst.',
  },
  {
    id: 'video-rolling-motion',
    name: 'Rolling Motion',
    img: 'https://lazykiwi.oss-accelerate.aliyuncs.com/web-assets/pic-references/home-cameramotion/rolling motion.png',
    prompt: 'Roll the frame through a playful kinetic camera move.',
  },
  {
    id: 'video-zoom-out',
    name: 'Zoom Out',
    img: 'https://lazykiwi.oss-accelerate.aliyuncs.com/web-assets/pic-references/home-cameramotion/zoom out.png',
    prompt: 'Pull the camera away to reveal a wider, more surprising scene.',
  },
  {
    id: 'video-whip-pan',
    name: 'Whip Pan',
    img: 'https://lazykiwi.oss-accelerate.aliyuncs.com/web-assets/pic-references/home-cameramotion/whip pan.png',
    prompt: 'Swipe the camera sideways with fast cinematic motion blur.',
  },
  {
    id: 'video-360-rotation',
    name: '360 Rotation',
    img: 'https://lazykiwi.oss-accelerate.aliyuncs.com/web-assets/pic-references/home-cameramotion/360 rotation.png',
    prompt: 'Orbit around the subject with a smooth 360-degree camera move.',
  },
  {
    id: 'video-flying-camera',
    name: 'Flying Camera',
    img: 'https://lazykiwi.oss-accelerate.aliyuncs.com/web-assets/pic-references/home-cameramotion/flying cam transition.png',
    prompt: 'Fly over the scene with a dynamic aerial camera transition.',
  },
  {
    id: 'video-explosion',
    name: 'Explosion',
    img: 'https://lazykiwi.oss-accelerate.aliyuncs.com/web-assets/pic-references/home-videoeffects/explosion.png',
    prompt: 'Add a stylized cinematic explosion effect behind the subject.',
  },
  {
    id: 'video-disintegration',
    name: 'Disintegration',
    img: 'https://lazykiwi.oss-accelerate.aliyuncs.com/web-assets/pic-references/home-videoeffects/disintegration.png',
    prompt: 'Let the subject dissolve into elegant particles with a cinematic motion trail.',
  },
  {
    id: 'video-money-rain',
    name: 'Money Rain',
    img: 'https://lazykiwi.oss-accelerate.aliyuncs.com/web-assets/pic-references/home-videoeffects/money rain.png',
    prompt: 'Make money fall through the scene with a bold creator-style effect.',
  },
];

export const LANDING_PHOTO_EFFECT_TEMPLATES = [
  {
    id: 'photo-xray-image',
    name: 'X-Ray Image',
    beforeImg: 'https://lazykiwi.oss-accelerate.aliyuncs.com/web-assets/assets/landing/image template/xray-before.jpg',
    afterImg: 'https://lazykiwi.oss-accelerate.aliyuncs.com/web-assets/assets/landing/image template/xray-after.png',
    prompt: 'Apply a playful x-ray style reveal while keeping the subject clean and polished.',
    chipLabel: 'X-Ray Image',
    category: 'Scan',
    outputBadge: 'Reveal',
    accent: '#38BDF8',
  },
  {
    id: 'photo-dirty-lens',
    name: 'Dirty Lens',
    beforeImg: 'https://lazykiwi.oss-accelerate.aliyuncs.com/web-assets/assets/landing/image template/dirty-before.jpg',
    afterImg: 'https://lazykiwi.oss-accelerate.aliyuncs.com/web-assets/assets/landing/image template/dirty-after.png',
    prompt: 'Add a gritty dirty lens overlay for a cinematic street-photo feeling.',
    chipLabel: 'Dirty Lens',
    category: 'Overlay',
    outputBadge: 'Texture',
    accent: '#14B8A6',
  },
  {
    id: 'photo-metallic-filter',
    name: 'Metallic Filter',
    beforeImg: 'https://lazykiwi.oss-accelerate.aliyuncs.com/web-assets/assets/landing/image template/metallic-before.jpg',
    afterImg: 'https://lazykiwi.oss-accelerate.aliyuncs.com/web-assets/assets/landing/image template/metallic-after.png',
    prompt: 'Transform the subject into a shiny metallic editorial portrait.',
    chipLabel: 'Metallic Filter',
    category: 'Editorial',
    outputBadge: 'Finish',
    accent: '#A78BFA',
  },
];
